[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_VERSION = "9.6.7"
  CI = "false"

# Redirection SPA pour le routage client-side
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# En-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"

# Paramètres de build
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["lucide-react"]

# Paramètres de build pour Vite
[context.production.environment]
  VITE_API_URL = "/api"
  NODE_OPTIONS = "--openssl-legacy-provider"

# Configuration pour les branches
[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"

[context.branch-deploy]
  command = "npm install --legacy-peer-deps && npm run build"

[context.production]
  command = "npm install --legacy-peer-deps && npm run build"
